# Generated by Django 3.2.8 on 2022-02-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220209_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sent_replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100)),
                ('reply', models.TextField(max_length=500)),
                ('message_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
            ],
        ),
    ]
